
developer_token = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjNHM0ZOV0ZIM1ciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJRNDc0M1Y2M1NCIiwiZXhwIjoxNzA5NzU5MDcxLCJpYXQiOjE3MDk3MTU4NzF9.7uiQeHzpecrqGO7uZnmGmmYYprMN9V6NzjaqB7saKKFC-HXmWrCq3HlNTTEpCyJRU2KtZSSoUDR-NrhtWNcdaA"


def get_token():
    return developer_token

